apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-oppdrag
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8087
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readyness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvfamilie-oppdrag
        mountPath: /secret/serviceuser
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 500m
  ingresses:
    - https://familie-oppdrag.dev-fss-pub.nais.io
    - https://familie-oppdrag.dev.intern.nav.no
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ks-sak
        - application: familie-ba-sak-lokal
          cluster: dev-gcp
        - application: familie-ba-sak
          cluster: dev-gcp
        - application: familie-ks-sak
          cluster: dev-gcp
        - application: familie-tilbake
          cluster: dev-gcp
        - application: familie-tilbake-lokal
          cluster: dev-gcp
        - application: familie-ef-sak
          cluster: dev-gcp
        - application: familie-ef-sak-lokal
          cluster: dev-gcp
        - application: familie-ef-iverksett
          cluster: dev-gcp
        - application: familie-ef-iverksett-lokal
          cluster: dev-gcp
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
    - name: JAVA_OPTS
      value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
