apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: utsjekk-oppdrag
  namespace: helved
  labels:
    team: helved

spec:
  image: {{ image }}
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readyness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: {{ limitsMemory }}
    requests:
      memory: {{ requestsMemory }}
      cpu: {{ requestsCpu }}
  secureLogs:
    enabled: true
  ingresses:
  {{#each ingresses as |url|}}
      - {{ url }}
  {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: utsjekk
    outbound:
      external:
        - host: {{ mqHostname }}
          ports:
            - port: {{ mqPort }}
  envFrom:
    - secret: utsjekk-oppdrag
  env:
    - name: JAVA_OPTS
      value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
    - name: MQ_HOSTNAME
      value: {{ mqHostname }}
    - name: MQ_PORT
      value: "{{ mqPort }}"
    - name: SPRING_PROFILES_ACTIVE
      value: {{ springProfil }}
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: {{ postgres_version }} # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        databases:
          - name: utsjekk-oppdrag
            envVarPrefix: DB
        diskAutoresize: true
        tier: {{ db_tier }}
        cascadingDelete: false
        highAvailability: true
        pointInTimeRecovery: true
        collation: nb_NO.UTF8
        diskType: SSD
        maintenance:
          day: 4
          hour: 23
        flags:
          - name: max_connections
            value: "100"
