apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: utsjekk-oppdrag-simulering
  namespace: helved
  labels:
    team: helved

spec:
  image: {{ image }}
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: {{ limitsMemory }}
    requests:
      memory: {{ requestsMemory }}
      cpu: {{ requestsCpu }}
  secureLogs:
    enabled: true
  ingresses:
  {{#each ingresses as |url|}}
      - {{ url }}
  {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: utsjekk
    outbound:
      external:
        - host: {{ simulering_hostname }}
        - host: {{ sts_hostname }}
  envFrom:
    - secret: utsjekk-oppdrag-simulering
  env:
    - name: JAVA_OPTS
      value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
    - name: SPRING_PROFILES_ACTIVE
      value: {{ springProfil }}
  azure:
    application:
      enabled: true
