/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dp.oppdrag

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest, "app should be created")
    }
}
