application:
  name: utsjekk-oppdrag

server:
  servlet:
    context-path: /

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main.banner-mode: "off"
  main:
    allow-bean-definition-overriding: true

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "isAlive"

springdoc:
  packagesToScan: no.nav.utsjekk.simulering
  pathsToMatch: /v3/api-docs,/**
  swagger-ui:
    disable-swagger-default-url: true

srv:
  username: srvdp-simulering
  password: ${servicebruker_passord}

DP_IVERKSETT_CLIENT_ID: ""
AZURE_APP_WELL_KNOWN_URL: ""