name: Bygg med maven
on: [pull_request, workflow_dispatch]

env:
  IMAGE: ghcr.io/navikt/dp-oppdrag:${{ github.sha }}
jobs:
  build:
    name: Bygg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --no-transfer-progress package verify --settings .m2/maven-settings.xml --file pom.xml