name: utsjekk-oppdrag Build-Deploy
on:
  push:
    paths:
      - 'utsjekk-oppdrag-app/**'
      - 'utsjekk-oppdrag-felles/**'
      - '.nais/oppdrag-**'
      - 'pom.xml'
      - '.github/workflows/build-and-deploy-oppdrag.yml'
    branches-ignore:
      - 'dependabot/**'

jobs:
  build:
    name: Bygg app/image, push til github
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --no-transfer-progress package verify --settings .m2/maven-settings.xml --file pom.xml

      - name: Push docker image til GAR og signer
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: helved
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          docker_context: ./utsjekk-oppdrag-app

  deploy-dev:
    name: Deploy to dev-gcp
    needs: build
    permissions:
      contents: write
      id-token: write
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: nais/deploy/actions/deploy@v2
          env:
            CLUSTER: dev-gcp
            RESOURCE: .nais/oppdrag-nais.yaml
            IMAGE: ${{ needs.build.outputs.image }}
            VAR: image=${{ needs.build.outputs.image }}
            VARS: .nais/oppdrag-vars-dev.yaml

  deploy-prod:
    name: Deploy to prod-gcp
    needs: [build,deploy-dev]
    permissions:
      contents: write
      id-token: write
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/oppdrag-nais.yaml
          IMAGE: ${{ needs.build.outputs.image }}
          VAR: image=${{ needs.build.outputs.image }}
          VARS: .nais/oppdrag-vars-prod.yaml
